### ISSUE TITLE
USER STORY: Food & Drink View

### ISSUE THREAD

**Issue by Dee68** [Dee68/milestone_project4#20]
As a **User** I can **view the food and drink menu** so that **I can decide wether to eat at the business**
### Acceptance Criteria
All users should be able to view the food and drink links
### Tasks:
- [x] - Create models food and drink
- [x] - Create templates correspondingly
- [x] - Create urls correspondingly
- [x] - Create view logic to implement it.

**Comment by Dee68** [comment]
Done.
