### ISSUE TITLE
Validation:

### ISSUE THREAD

**Issue by Dee68** [Dee68/milestone_project4#4]
As a **Site User** I can **know if my input values a valid** so that **I do not mistakenly input errors**
### Acceptance Criteria
Validate all input fields to fulfill requirements in model and business rules
### Tasks:
- [x] - Create models with requirements
- [x] - Create templates and reserve places to show validation errors
- [x] - Create a corresponding view logic to implement requirements.
