### ISSUE TITLE
Reservation:

### ISSUE THREAD

**Issue by Dee68** [Dee68/milestone_project4#5]
As a **Site user** I can **Reserve a Table in advance** so that **have a dinner or lunch with friends and family**
### Acceptance Criteria
Allow logged in user to make a reservation with correct data input.

### Tasks:
- [x] - Create a model to represent reservation in the database
- [x]  - Create a corresponding template/form
- [x]  - Create view logic to handle correct input
- [x]  - Create corresponding url
