### ISSUE TITLE
USER STORY: Navigation

### ISSUE THREAD

**Issue by Dee68** [Dee68/milestone_project4#9]
As a **User** I can **navigate across the site** so that **I can move to each feature of the site easily**
### Acceptance Criteria
The site should have a navigation bar with a footer with all links showing corresponding pages.
### Tasks:
- [x] - create a template with navbar and footer elements
- [x] - create corresponding links to pages
- [x] - create view logic to  link urls

**Comment by Dee68** [comment]
completed
